
a=int(input("Enter Num1:"))
b=int(input("Enter Num2:"))
print("Addition:")
print("a+b=",a+b)
print("subtraction:")
print("a-b=",a-b)
print("multiplication:")
print("a*b=",a*b)
print(" division:")
print("a/b=",a/b)
